"""
This type stub file was generated by pyright.
"""

from .abstract_nodes import List as AbstractList
from .ast import Token

class List(AbstractList):
    ...


class NumExprEvaluate(Token):
    """represents a call to :class:`numexpr`s :func:`evaluate`"""
    _fields = ...


