"""
This type stub file was generated by pyright.
"""

from .simplify import besselsimp, hypersimilar, hypersimp, kroneckersimp, logcombine, nsimplify, posify, separatevars, signsimp, simplify
from .fu import FU, fu
from .sqrtdenest import sqrtdenest
from .cse_main import cse
from .epathtools import EPath, epath
from .hyperexpand import hyperexpand
from .radsimp import collect, collect_const, denom, fraction, numer, radsimp, rcollect
from .trigsimp import exptrigsimp, trigsimp
from .powsimp import powdenest, powsimp
from .combsimp import combsimp
from .gammasimp import gammasimp
from .ratsimp import ratsimp, ratsimpmodprime

"""The module helps converting SymPy expressions into shorter forms of them.

for example:
the expression E**(pi*I) will be converted into -1
the expression (x+x)**2 will be converted into 4*x**2
"""
__all__ = ['simplify', 'hypersimp', 'hypersimilar', 'logcombine', 'separatevars', 'posify', 'besselsimp', 'kroneckersimp', 'signsimp', 'nsimplify', 'FU', 'fu', 'sqrtdenest', 'cse', 'epath', 'EPath', 'hyperexpand', 'collect', 'rcollect', 'radsimp', 'collect_const', 'fraction', 'numer', 'denom', 'trigsimp', 'exptrigsimp', 'powsimp', 'powdenest', 'combsimp', 'gammasimp', 'ratsimp', 'ratsimpmodprime']
