"""
This type stub file was generated by pyright.
"""

from .pretty import pager_print, pprint, pprint_try_use_unicode, pprint_use_unicode, pretty, pretty_print

"""ASCII-ART 2D pretty-printer"""
__all__ = ['pretty', 'pretty_print', 'pprint', 'pprint_use_unicode', 'pprint_try_use_unicode', 'pager_print']
