"""
This type stub file was generated by pyright.
"""

from sympy.polys.domains.finitefield import FiniteField
from sympy.utilities import public

"""Implementation of :class:`GMPYFiniteField` class. """
@public
class GMPYFiniteField(FiniteField):
    """Finite field based on GMPY integers. """
    alias = ...
    def __init__(self, mod, symmetric=...) -> None:
        ...
    


