"""
This type stub file was generated by pyright.
"""

from sympy.polys.domains.domain import Domain
from sympy.utilities import public

"""Implementation of :class:`SimpleDomain` class. """
@public
class SimpleDomain(Domain):
    """Base class for simple domains, e.g. ZZ, QQ. """
    is_Simple = ...
    def inject(self, *gens): # -> PolynomialRing:
        """Inject generators into this domain. """
        ...
    


