"""
This type stub file was generated by pyright.
"""

from sympy.combinatorics.permutations import Cycle, Permutation
from sympy.combinatorics.prufer import Prufer
from sympy.combinatorics.generators import alternating, cyclic, dihedral, symmetric
from sympy.combinatorics.subsets import Subset
from sympy.combinatorics.partitions import IntegerPartition, Partition, RGS_enum, RGS_rank, RGS_unrank
from sympy.combinatorics.polyhedron import Polyhedron, cube, dodecahedron, icosahedron, octahedron, tetrahedron
from sympy.combinatorics.perm_groups import Coset, PermutationGroup, SymmetricPermutationGroup
from sympy.combinatorics.group_constructs import DirectProduct
from sympy.combinatorics.graycode import GrayCode
from sympy.combinatorics.named_groups import AbelianGroup, AlternatingGroup, CyclicGroup, DihedralGroup, RubikGroup, SymmetricGroup
from sympy.combinatorics.pc_groups import Collector, PolycyclicGroup
from sympy.combinatorics.free_groups import free_group

__all__ = ['Permutation', 'Cycle', 'Prufer', 'cyclic', 'alternating', 'symmetric', 'dihedral', 'Subset', 'Partition', 'IntegerPartition', 'RGS_rank', 'RGS_unrank', 'RGS_enum', 'Polyhedron', 'tetrahedron', 'cube', 'octahedron', 'dodecahedron', 'icosahedron', 'PermutationGroup', 'Coset', 'SymmetricPermutationGroup', 'DirectProduct', 'GrayCode', 'SymmetricGroup', 'DihedralGroup', 'CyclicGroup', 'AlternatingGroup', 'AbelianGroup', 'RubikGroup', 'PolycyclicGroup', 'Collector', 'free_group']
