"""
This type stub file was generated by pyright.
"""

from .iterables import capture, cartes, dict_merge, flatten, group, has_dups, has_variety, numbered_symbols, postfixes, prefixes, reshape, rotations, sift, subsets, take, topological_sort, unflatten, variations
from .misc import filldedent
from .lambdify import lambdify
from .decorator import memoize_property, public, threaded, xthreaded
from .timeutils import timed

"""This module contains some general purpose utilities that are used across
SymPy.
"""
__all__ = ['flatten', 'group', 'take', 'subsets', 'variations', 'numbered_symbols', 'cartes', 'capture', 'dict_merge', 'prefixes', 'postfixes', 'sift', 'topological_sort', 'unflatten', 'has_dups', 'has_variety', 'reshape', 'rotations', 'filldedent', 'lambdify', 'threaded', 'xthreaded', 'public', 'memoize_property', 'timed']
