"""
This type stub file was generated by pyright.
"""

from .indexed import Idx, Indexed, IndexedBase
from .index_methods import get_contraction_structure, get_indices
from .functions import shape
from .array import Array, DenseNDimArray, ImmutableDenseNDimArray, ImmutableSparseNDimArray, MutableDenseNDimArray, MutableSparseNDimArray, NDimArray, SparseNDimArray, derive_by_array, permutedims, tensorcontraction, tensordiagonal, tensorproduct

"""A module to manipulate symbolic objects with indices including tensors

"""
__all__ = ['IndexedBase', 'Idx', 'Indexed', 'get_contraction_structure', 'get_indices', 'shape', 'MutableDenseNDimArray', 'ImmutableDenseNDimArray', 'MutableSparseNDimArray', 'ImmutableSparseNDimArray', 'NDimArray', 'tensorproduct', 'tensorcontraction', 'tensordiagonal', 'derive_by_array', 'permutedims', 'Array', 'DenseNDimArray', 'SparseNDimArray']
