"""
This type stub file was generated by pyright.
"""

from .slice import MatrixSlice
from .blockmatrix import BlockDiagMatrix, BlockMatrix, block_collapse, blockcut
from .companion import CompanionMatrix
from .funcmatrix import FunctionMatrix
from .inverse import Inverse
from .matadd import MatAdd
from .matexpr import MatrixExpr, MatrixSymbol, matrix_symbols
from .matmul import MatMul
from .matpow import MatPow
from .trace import Trace, trace
from .determinant import Determinant, Permanent, det, per
from .transpose import Transpose
from .adjoint import Adjoint
from .hadamard import HadamardPower, HadamardProduct, hadamard_power, hadamard_product
from .diagonal import DiagMatrix, DiagonalMatrix, DiagonalOf, diagonalize_vector
from .dotproduct import DotProduct
from .kronecker import KroneckerProduct, combine_kronecker, kronecker_product
from .permutation import MatrixPermute, PermutationMatrix
from .sets import MatrixSet
from .special import Identity, OneMatrix, ZeroMatrix

""" A module which handles Matrix Expressions """
__all__ = ['MatrixSlice', 'BlockMatrix', 'BlockDiagMatrix', 'block_collapse', 'blockcut', 'FunctionMatrix', 'CompanionMatrix', 'Inverse', 'MatAdd', 'Identity', 'MatrixExpr', 'MatrixSymbol', 'ZeroMatrix', 'OneMatrix', 'matrix_symbols', 'MatrixSet', 'MatMul', 'MatPow', 'Trace', 'trace', 'Determinant', 'det', 'Transpose', 'Adjoint', 'hadamard_product', 'HadamardProduct', 'hadamard_power', 'HadamardPower', 'DiagonalMatrix', 'DiagonalOf', 'DiagMatrix', 'diagonalize_vector', 'DotProduct', 'kronecker_product', 'KroneckerProduct', 'combine_kronecker', 'PermutationMatrix', 'MatrixPermute', 'Permanent', 'per']
