"""
This type stub file was generated by pyright.
"""

def print_gtk(x, start_viewer=...): # -> None:
    """Print to Gtkmathview, a gtk widget capable of rendering MathML.

    Needs libgtkmathview-bin"""
    ...

